<?php
/**
 * theme-setup.php
 */

/**
 * Suppress errors generated by specified WordPress plugins.
 *
 * @link http://plugins.trac.wordpress.org/browser/ostrichcize/tags/0.1/ostrichcize.php#L146
 */
function uap_custom_error_handler( $errno, $errstr, $errfile, $errline ) {
  $patterns = array(
    'plugins/litespeed-cache',
  );

  foreach ( $patterns as $pattern ) {
    $pattern = str_replace( array( '/', '\\' ), DIRECTORY_SEPARATOR, $pattern );

    if ( false !== strpos( $errstr, $pattern ) || false !== strpos( $errfile, $pattern ) ) {
      return true;
    }
  }
  return false;
}
set_error_handler( 'uap_custom_error_handler' );


/**
 * Show page template in header
 */
function uap_show_page_template() {
  if ( !uap_user_is_dev() ) {
    return;
  }
  global $template;
  echo '<pre style="padding: 1em; margin: 0; font-size: 0.875rem; font-family: monospace;">';
  print_r( $template );
  echo '</pre>';
}
// add_action( 'wp_head', 'uap_show_page_template' );


/**
 * Remove custom columns added by Yoast SEO plugin
 *
 * @link https://gist.github.com/amboutwe/18558a7e681e36c6bfe6e4fb647265ce
 */
function uap_remove_yoast_seo_columns( $columns ) {
  // unset( $columns['wpseo-score'] );
  // unset( $columns['wpseo-score-readability'] );
  unset( $columns['wpseo-title'] );
  unset( $columns['wpseo-metadesc'] );
  unset( $columns['wpseo-focuskw']);
  unset( $columns['wpseo-links']);
  unset( $columns['wpseo-linked']);
  // unset( $columns['wpseo-cornerstone']);
  return $columns;
}
// post types
add_filter( 'manage_edit-post_columns', 'uap_remove_yoast_seo_columns', 10, 1 );
add_filter( 'manage_edit-page_columns', 'uap_remove_yoast_seo_columns', 10, 1 );

// custom post types
add_filter( 'manage_edit-hearing_columns', 'uap_remove_yoast_seo_columns', 10, 1 );
add_filter( 'manage_edit-incident_columns', 'uap_remove_yoast_seo_columns', 10, 1 );
add_filter( 'manage_edit-sighting_columns', 'uap_remove_yoast_seo_columns', 10, 1 );
add_filter( 'manage_edit-whistleblower_columns', 'uap_remove_yoast_seo_columns', 10, 1 );

// taxonomies
add_filter( 'manage_edit-category_columns', 'uap_remove_yoast_seo_columns', 10, 1 );
add_filter( 'manage_edit-post_tag_columns', 'uap_remove_yoast_seo_columns', 10, 1 );


/**
 * Add Google Maps API key for ACF
 */
function bc_acf_google_maps_key() {
  if ( get_field( 'google_maps_api_key', 'option' ) ) {
    acf_update_setting( 'google_api_key', get_field( 'google_maps_api_key', 'option' ) );
  }
}
add_action( 'acf/init', 'bc_acf_google_maps_key' );


/**
 * Add "DEV" label to admin menu
 */
function bc_add_admin_env_label( WP_Admin_Bar $wp_admin_bar ) {
  if ( !uap_user_is_dev() ) {
    return;
  }
  if ( uap_is_local() ) {
    $title = '<span style="color: #2bbf26;">DEV</span>';
  } else {
    $title = '<span style="color: #f73e4d;">PROD</span>';
  }

  $wp_admin_bar->add_menu( array(
    'id' => 'admin-env-label',
    'parent' => 'top-secondary',
    'group' => null,
    'title' => $title,
    'href' => admin_url(),
  ) );
}
add_action( 'admin_bar_menu', 'bc_add_admin_env_label', 100 );
